---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hanzo.ai
  resources:
  - baseapps
  - hanzodatastores
  - hanzodns
  - hanzogateways
  - hanzoingresses
  - hanzompcs
  - hanzonetworks
  - hanzoplatforms
  - hanzoservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hanzo.ai
  resources:
  - baseapps/finalizers
  - hanzodatastores/finalizers
  - hanzodns/finalizers
  - hanzogateways/finalizers
  - hanzoingresses/finalizers
  - hanzompcs/finalizers
  - hanzonetworks/finalizers
  - hanzoplatforms/finalizers
  - hanzoservices/finalizers
  verbs:
  - update
- apiGroups:
  - hanzo.ai
  resources:
  - baseapps/status
  - hanzodatastores/status
  - hanzodns/status
  - hanzogateways/status
  - hanzoingresses/status
  - hanzompcs/status
  - hanzonetworks/status
  - hanzoplatforms/status
  - hanzoservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kms.hanzo.ai
  resources:
  - kmssecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
